### ISSUE TITLE
world chat 2.0 feedback

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-world-chat#18]
tyvm....@wizzymore
 The new version can now click on the player's name to whisper,It's really a good job
I have some bugs that need feedback:

1.GM chat does not display icon
login game,enter .gm on . then enter. Chata ,not show GM icon
![20201228091620](https://user-images.githubusercontent.com/18187177/103183433-62fb0880-48ed-11eb-8c96-d5b6405b2977.jpg)
2.World chat doesn't show player level
3.After /join world , can't talk to. Chat players 
![20201228085521](https://user-images.githubusercontent.com/18187177/103183339-b91b7c00-48ec-11eb-8685-f8d7fde72a95.jpg)
![20201228085559](https://user-images.githubusercontent.com/18187177/103183345-c46ea780-48ec-11eb-88b3-bf3db7a03c97.png)
They are still two different channels
4.Unable to save.chat channel log,who said what

**Comment by wizzymore** [comment]
Hi,

1. To display the icon you need to have .gm chat on
2. This needs to be added by yourself, try this:
Change this:
https://github.com/azerothcore/mod-world-chat/blob/fdb56a76499d8ff563cb7cff119730e23080c644/src/WorldChat.cpp#L157
To this:
```cpp
snprintf(message, 1024, "[World][%s][%s|Hplayer:%s|h%u:%s|h|r]: %s%s|r", world_chat_TeamIcon[sender->GetTeamId()].c_str(), world_chat_ClassColor[sender->getClass() - 1].c_str(), sender->GetName().c_str(), sender->getLevel(), sender->GetName().c_str(), WORLD_CHAT_WHITE.c_str(), msg);
```
This will make the chat like this:
[World][Alliance][80:Wizzymore] instead of the default [World][Alliance][Wizzymore]

- With .gm chat off
![image](https://user-images.githubusercontent.com/25827787/103184439-f9650500-48c0-11eb-9599-b336dfc1b957.png)
![image](https://user-images.githubusercontent.com/25827787/103184447-fff37c80-48c0-11eb-9bfb-bc424ce2af6d.png)
![image](https://user-images.githubusercontent.com/25827787/103184454-04b83080-48c1-11eb-8a18-53f2eca2e293.png)
- With .gm chat on
![image](https://user-images.githubusercontent.com/25827787/103184461-0a157b00-48c1-11eb-8b4f-a0f76ae728e9.png)
![image](https://user-images.githubusercontent.com/25827787/103184471-13064c80-48c1-11eb-8069-40c1bda4f07d.png)

3. The channel you join is case sensitive, by default it is "World" not "world".
4. This is not a function of the module, yet.

**Comment by mpfans** [comment]
> Hi,
> 
> 1. To display the icon you need to have .gm chat on
> 2. This needs to be added by yourself, try this:
>    Change this:
>    https://github.com/azerothcore/mod-world-chat/blob/fdb56a76499d8ff563cb7cff119730e23080c644/src/WorldChat.cpp#L157
>    
>    To this:
> 
> ```c++
> snprintf(message, 1024, "[World][%s][%s|Hplayer:%s|h%u:%s|h|r]: %s%s|r", world_chat_TeamIcon[sender->GetTeamId()].c_str(), world_chat_ClassColor[sender->getClass() - 1].c_str(), sender->GetName().c_str(), sender->getLevel(), sender->GetName().c_str(), WORLD_CHAT_WHITE.c_str(), msg);
> ```
> 
> This will make the chat like this:
> [World][Alliance][80:Wizzymore] instead of the default [World][Alliance][Wizzymore]
> 
> * With .gm chat off
>   ![image](https://user-images.githubusercontent.com/25827787/103184439-f9650500-48c0-11eb-9599-b336dfc1b957.png)
>   ![image](https://user-images.githubusercontent.com/25827787/103184447-fff37c80-48c0-11eb-9bfb-bc424ce2af6d.png)
>   ![image](https://user-images.githubusercontent.com/25827787/103184454-04b83080-48c1-11eb-8a18-53f2eca2e293.png)
> * With .gm chat on
>   ![image](https://user-images.githubusercontent.com/25827787/103184461-0a157b00-48c1-11eb-8b4f-a0f76ae728e9.png)
>   ![image](https://user-images.githubusercontent.com/25827787/103184471-13064c80-48c1-11eb-8069-40c1bda4f07d.png)
> 
> 1. The channel you join is case sensitive, by default it is "World" not "world".
> 2. This is not a function of the module, yet.

thank you very much! @wizzymore  You are so great!

everything else succeeded!Thanks again!

Now you can log chat,but maybe there's something wrong with the coding

![20201228103217](https://user-images.githubusercontent.com/18187177/103185625-25e84380-48f8-11eb-9a26-21bcaefc659a.jpg)
![20201228103237](https://user-images.githubusercontent.com/18187177/103185632-297bca80-48f8-11eb-92d3-bdeedd96ad9c.jpg)

**Comment by wizzymore** [comment]
That's what i mean by "in work", because i change the message to -1 it currently get's deleted so it will not send the message on the normal chat, if i can fix this, i will do an update so it doesn't send the normal channel message but still logs the chat correctly.

**Comment by mpfans** [comment]
> That's what i mean by "in work", because i change the message to -1 it currently get's deleted so it will not send the message on the normal chat, if i can fix this, i will do an update so it doesn't send the normal channel message but still logs the chat correctly.
Can I add you  on discord?
